nelmio_api_doc:
    documentation:
        info:
            title: API Prueba Cuatroochenta
            description: La API que he hecho como prueba para entrar a trabajar en Cuatroochenta
            version: 1.0.0

    areas:
        path_patterns:
            - ^/api(?!/doc$)
