controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


########## USER ##########

login:
    path:       /api/login
    methods:    POST
    controller: App\Controller\ApiLoginController::login
    defaults:
        _format: json


logout:
    path:       /api/logout
    methods:    POST
    controller: App\Controller\ApiLoginController::logout

user_register:
    path:       /api/register
    controller: App\Controller\RegistrationController::register
    methods:    POST


######### SENSOR #########

sensor_list:
    path:       /api/sensor/list
    controller: App\Controller\SensorController::list
    methods:    GET

sensor_create:
    path:       /api/sensor/create
    controller: App\Controller\SensorController::create
    methods:    POST

sensor_update:
    path:       /api/sensor/update/{id}
    controller: App\Controller\SensorController::update
    methods:    POST

sensor_delete:
    path:       /api/sensor/delete/{id}
    controller: App\Controller\SensorController::delete
    methods:    DELETE


########## WINE ##########

wine_list:
    path:       /api/wine/list
    controller: App\Controller\WineController::list
    methods:    GET

wine_create:
    path:       /api/wine/create
    controller: App\Controller\WineController::create
    methods:    POST

wine_update:
    path:       /api/wine/update/{id}
    controller: App\Controller\WineController::update
    methods:    POST

wine_delete:
    path:       /api/wine/delete/{id}
    controller: App\Controller\WineController::delete
    methods:    DELETE

######## MEASURING #######

measuring_list:
    path:       /api/measuring/list
    controller: App\Controller\MeasuringController::list
    methods:    GET

measuring_create:
    path:       /api/measuring/create
    controller: App\Controller\MeasuringController::create
    methods:    POST

measuring_update:
    path:       /api/measuring/update/{id}
    controller: App\Controller\MeasuringController::update
    methods:    POST

measuring_delete:
    path:       /api/measuring/delete/{id}
    controller: App\Controller\MeasuringController::delete
    methods:    DELETE